name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Chrome Addon Action
      uses: trmcnvn/chrome-addon@v1
      with:
        # extension is only necessary when updating an existing addon,
        # omitting it will create a new addon
        extension: nepakmljodobhlbbkpobblnifmhclemh
        zip: build/pageliner.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
